--*************************************************************************--
-- Title: Final Project - inserting data imported from from mackaroo
-- Author: GyubeomKim
-- Desc: This file shows inserting data
-- Change Log: When,Who,What
-- 2018-07-23,GyubeomKim,Created File
--**************************************************************************--
Use MyFinalProjectDB_GyubeomKim;
go

--Inserting Data--
--10 Clinics--
insert into dbo.Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress1, ClinicAddress2, ClinicCity, ClinicState, ClinicZipcode) values ('Dermatology Clinic', '734-199-4163', '2813 Weeping Birch Terrace', null, 'Detroit', 'MI', '48211');
insert into dbo.Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress1, ClinicAddress2, ClinicCity, ClinicState, ClinicZipcode) values ('The Clinic', '614-451-8424', '05769 Jay Terrace', null, 'Columbus', 'OH', '43284');
insert into dbo.Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress1, ClinicAddress2, ClinicCity, ClinicState, ClinicZipcode) values ('Vision Clinic', '414-656-6731', '5527 Michigan Way', null, 'Milwaukee', 'WI', '53263');
insert into dbo.Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress1, ClinicAddress2, ClinicCity, ClinicState, ClinicZipcode) values ('Maternal and Infant Care Clinic', '646-715-6644', '3 Mitchell Circle', null, 'New York City', 'NY', '10060');
insert into dbo.Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress1, ClinicAddress2, ClinicCity, ClinicState, ClinicZipcode) values ('Breast Health Clini', '206-784-2835', '3 Prairie Rose Road', null, 'Seattle', 'WA', '98127');
insert into dbo.Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress1, ClinicAddress2, ClinicCity, ClinicState, ClinicZipcode) values ('Community Psychiatric Clinic', '904-647-9434', '579 Porter Street', null, 'Jacksonville', 'FL', '32215');
insert into dbo.Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress1, ClinicAddress2, ClinicCity, ClinicState, ClinicZipcode) values ('Cancer Clinic', '571-710-6855', '60101 Glendale Parkway', null, 'Arlington', 'VA', '22217');
insert into dbo.Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress1, ClinicAddress2, ClinicCity, ClinicState, ClinicZipcode) values ('Cardiology & Heart Clinic', '613-387-0627', '54 Cambridge Point', null, 'Boston', 'MA', '02283');
insert into dbo.Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress1, ClinicAddress2, ClinicCity, ClinicState, ClinicZipcode) values ('Cleveland Clinic', '814-457-0216', '4105 Sommers Way', null, 'Erie', 'PA', '16565');
insert into dbo.Clinics (ClinicName, ClinicPhoneNumber, ClinicAddress1, ClinicAddress2, ClinicCity, ClinicState, ClinicZipcode) values ('Mayo Clinic', '415-555-6545', '2122 Buell Drive', null, 'San Francisco', 'CA', '94147');
Go
Select * From vClinics;

--10 Doctors--
insert into dbo.Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress1, DoctorAddress2, DoctorCity, DoctorState, DoctorZipcode) values ('Bay', 'Latliff', '314-510-7935', '8736 Mallard Park', null, 'Saint Louis', 'MO', '63110');
insert into dbo.Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress1, DoctorAddress2, DoctorCity, DoctorState, DoctorZipcode) values ('Chrotoem', 'Hinken', '224-640-8441', '369 Melby Trail', null, 'Chicago', 'IL', '60604');
insert into dbo.Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress1, DoctorAddress2, DoctorCity, DoctorState, DoctorZipcode) values ('Daisey', 'Narrie', '562-766-1160', '6704 Esker Pass', null, 'Long Beach', 'CA', '90840');
insert into dbo.Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress1, DoctorAddress2, DoctorCity, DoctorState, DoctorZipcode) values ('Robin', 'Goldine', '512-790-7411', '2495 American Ash Junction', null, 'Austin', 'TX', '78710');
insert into dbo.Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress1, DoctorAddress2, DoctorCity, DoctorState, DoctorZipcode) values ('Arch', 'Ronchka', '256-555-6226', '7 Straubel Avenue', null, 'Huntsville', 'AL', '35815');
insert into dbo.Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress1, DoctorAddress2, DoctorCity, DoctorState, DoctorZipcode) values ('Wilfrid', 'Mulchrone', '412-254-1877', '9164 Spenser Park', null, 'Mc Keesport', 'PA', '15134');
insert into dbo.Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress1, DoctorAddress2, DoctorCity, DoctorState, DoctorZipcode) values ('Scotty', 'Glasbey', '754-582-5103', '9121 School Terrace', null, 'Fort Lauderdale', 'FL', '33336');
insert into dbo.Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress1, DoctorAddress2, DoctorCity, DoctorState, DoctorZipcode) values ('Vita', 'Gaish', '814-389-5924', '344 Springs Plaza', null, 'Johnstown', 'PA', '15906');
insert into dbo.Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress1, DoctorAddress2, DoctorCity, DoctorState, DoctorZipcode) values ('Hephzibah', 'Hilley', '215-831-7181', '0 7th Avenue', null, 'Philadelphia', 'PA', '19184');
insert into dbo.Doctors (DoctorFirstName, DoctorLastName, DoctorPhoneNumber, DoctorAddress1, DoctorAddress2, DoctorCity, DoctorState, DoctorZipcode) values ('Herc', 'Carlisle', '614-864-6460', '762 Dapin Park', null, 'Columbus', 'OH', '43215');
Go
Select * From vDoctors;

--100Patients--
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Mitch', 'Adlem', '818-178-1232', '05 Lotheville Plaza', null, 'Santa Monica', 'CA', '90405');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Maximilien', 'Crowne', '504-761-8355', '81357 Bultman Court', null, 'New Orleans', 'LA', '70116');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Mirabelle', 'Kovnot', '510-960-2347', '47 Sullivan Place', null, 'Oakland', 'CA', '94627');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Licha', 'Kimble', '808-169-6474', '3 Park Meadow Road', null, 'Honolulu', 'HI', '96815');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Aurelia', 'Rubi', '816-348-9588', '25878 Crowley Point', null, 'Kansas City', 'MO', '64153');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Celia', 'Bakeup', '412-999-2747', '46989 Eagle Crest Place', null, 'Mc Keesport', 'PA', '15134');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Brendon', 'Shippam', '712-556-8901', '84865 High Crossing Crossing', null, 'Sioux City', 'IA', '51105');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Gardy', 'Sidary', '973-225-9955', '314 Marcy Court', null, 'Paterson', 'NJ', '07522');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Lorrayne', 'Capey', '202-226-8464', '6890 Arapahoe Junction', null, 'Washington', 'DC', '20470');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Babb', 'Krysztowczyk', '612-920-1351', '330 Del Mar Junction', null, 'Saint Paul', 'MN', '55127');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Barnard', 'Lashbrook', '716-134-3150', '1 Hansons Junction', null, 'Buffalo', 'NY', '14210');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Germain', 'Churchward', '843-199-3960', '9718 Anthes Point', null, 'Charleston', 'SC', '29424');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Karlee', 'Ainslie', '419-603-4826', '99903 Northview Place', null, 'Toledo', 'OH', '43656');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Livvy', 'Betancourt', '704-500-0136', '127 Anzinger Crossing', null, 'Charlotte', 'NC', '28263');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Amery', 'Coils', '334-732-6209', '6019 Forest Run Place', null, 'Montgomery', 'AL', '36114');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Ashley', 'Flay', '812-675-7506', '10938 Burning Wood Park', null, 'Evansville', 'IN', '47737');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Mick', 'Biddles', '907-264-4196', '1 School Drive', null, 'Juneau', 'AK', '99812');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Lulita', 'Killich', '502-564-8273', '77 Cascade Terrace', null, 'Frankfort', 'KY', '40618');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Guthrey', 'Showers', '813-799-4200', '6 Summer Ridge Terrace', null, 'Tampa', 'FL', '33610');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Salomone', 'Gagie', '202-819-5345', '73282 Pond Place', null, 'Washington', 'DC', '20591');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Robers', 'Hartrick', '916-307-2233', '1 Scott Circle', null, 'Sacramento', 'CA', '95838');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Gallard', 'Clogg', '971-611-5934', '19859 Ridge Oak Way', null, 'Salem', 'OR', '97312');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Homer', 'Iacovuzzi', '202-603-5536', '4 Luster Hill', null, 'Washington', 'DC', '20022');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Dominique', 'Hazelhurst', '843-168-2407', '5369 Novick Place', null, 'Florence', 'SC', '29505');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Robinia', 'Roney', '619-273-1167', '782 Calypso Street', null, 'San Diego', 'CA', '92115');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Leah', 'Cathro', '203-649-0135', '5904 Montana Pass', null, 'Waterbury', 'CT', '06721');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Dru', 'Sykes', '920-626-8838', '117 American Point', null, 'Green Bay', 'WI', '54313');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Clint', 'Woodruffe', '323-932-7649', '60 Sunfield Terrace', null, 'Los Angeles', 'CA', '90076');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Blayne', 'Chafney', '509-294-1189', '0138 Springs Alley', null, 'Spokane', 'WA', '99220');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Reiko', 'Adaway', '856-276-4543', '28 Donald Alley', null, 'Camden', 'NJ', '08104');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Inesita', 'Aberhart', '773-816-6019', '5 Debra Hill', null, 'Chicago', 'IL', '60614');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Lorilee', 'Ferfulle', '225-136-3610', '6476 Norway Maple Parkway', null, 'Baton Rouge', 'LA', '70894');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Nester', 'Lusgdin', '850-864-9627', '4 Russell Point', null, 'Tallahassee', 'FL', '32314');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Orlan', 'O''Brian', '303-383-9025', '2 Melody Lane', null, 'Denver', 'CO', '80223');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Tremain', 'Le Gall', '954-599-3966', '06101 Melby Place', null, 'Boca Raton', 'FL', '33432');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Laverna', 'Gibb', '801-868-6125', '6594 Anhalt Point', null, 'Salt Lake City', 'UT', '84170');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Nora', 'Furnival', '904-289-9213', '372 Waywood Parkway', null, 'Jacksonville', 'FL', '32255');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Shandeigh', 'Breeds', '202-130-1195', '368 Transport Place', null, 'Washington', 'DC', '20215');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Noelle', 'Iacopetti', '917-334-8209', '17 Larry Street', null, 'Bronx', 'NY', '10474');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Reece', 'Penvarne', '573-359-1885', '3190 Waxwing Avenue', null, 'Jefferson City', 'MO', '65105');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Flore', 'Wyburn', '916-868-5363', '05 Crescent Oaks Terrace', null, 'Chico', 'CA', '95973');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Odey', 'Matevosian', '402-844-2128', '25 Sommers Circle', null, 'Omaha', 'NE', '68124');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Sean', 'Rielly', '914-283-3697', '93 Esch Road', null, 'Yonkers', 'NY', '10705');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Rad', 'Boram', '775-708-6083', '8978 Arizona Point', null, 'Reno', 'NV', '89519');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Hermann', 'Klulicek', '909-375-0245', '778 Fremont Place', null, 'Riverside', 'CA', '92505');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Chiarra', 'Jandl', '413-189-0837', '16257 Montana Crossing', null, 'Springfield', 'MA', '01129');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Haven', 'Blazhevich', '315-230-4668', '2 American Ash Alley', null, 'Syracuse', 'NY', '13224');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Rocky', 'Snassell', '843-748-2310', '49 Redwing Road', null, 'Charleston', 'SC', '29424');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Aldon', 'Broe', '616-416-5408', '1591 Manufacturers Lane', null, 'Grand Rapids', 'MI', '49518');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Salvador', 'Crevagh', '269-530-8088', '59 Swallow Pass', null, 'Kalamazoo', 'MI', '49006');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Basile', 'Sayes', '571-387-4040', '73 Westridge Pass', null, 'Arlington', 'VA', '22205');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Gardy', 'Traut', '952-694-8614', '2360 Division Trail', null, 'Young America', 'MN', '55564');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Ave', 'Gilbertson', '704-460-4621', '667 Brickson Park Park', null, 'Charlotte', 'NC', '28242');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Miguelita', 'Drinkale', '727-232-6709', '0 Stephen Plaza', null, 'Clearwater', 'FL', '34629');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Harris', 'Odd', '917-223-6165', '9002 Clove Point', null, 'New York City', 'NY', '10270');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Dorthea', 'Cockroft', '206-297-3246', '7 Hoepker Point', null, 'Seattle', 'WA', '98148');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Derril', 'Panting', '303-373-4029', '88614 Katie Street', null, 'Denver', 'CO', '80209');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Moina', 'Roches', '339-274-6136', '0795 Northport Hill', null, 'Woburn', 'MA', '01813');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Luise', 'McFie', '803-397-2907', '2670 Pankratz Crossing', null, 'Columbia', 'SC', '29208');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Averyl', 'Swiffen', '520-237-5866', '284 Leroy Court', null, 'Prescott', 'AZ', '86305');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Athena', 'Durie', '303-491-5317', '1 Northfield Court', null, 'Littleton', 'CO', '80161');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Dennis', 'Giacomo', '917-572-8693', '58071 Center Plaza', null, 'Bronx', 'NY', '10459');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Maynord', 'Bothe', '314-100-8943', '302 Blue Bill Park Lane', null, 'Saint Louis', 'MO', '63116');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Jo ann', 'Bontein', '312-995-0447', '455 Huxley Court', null, 'Chicago', 'IL', '60691');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Lemmy', 'Bryenton', '702-719-4572', '80811 Luster Hill', null, 'Las Vegas', 'NV', '89135');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Waldo', 'Bevan', '612-953-6927', '5 Shasta Lane', null, 'Minneapolis', 'MN', '55417');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Janella', 'Matyushkin', '503-193-5191', '9350 Sloan Lane', null, 'Portland', 'OR', '97229');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Giana', 'Bratton', '408-365-1191', '8840 Melby Place', null, 'San Jose', 'CA', '95194');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Tammie', 'Dusting', '305-249-7387', '01411 Banding Parkway', null, 'Miami', 'FL', '33283');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Windy', 'McNern', '704-810-5845', '85543 Melvin Terrace', null, 'Charlotte', 'NC', '28235');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Estrellita', 'Struther', '602-456-5452', '4386 Hallows Circle', null, 'Phoenix', 'AZ', '85072');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Waring', 'Emery', '859-178-5642', '38216 Oakridge Lane', null, 'Lexington', 'KY', '40576');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Martie', 'Elsip', '607-134-1246', '6236 Del Mar Lane', null, 'Elmira', 'NY', '14905');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Joellyn', 'Hadeke', '205-572-7388', '48 Bashford Pass', null, 'Birmingham', 'AL', '35242');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Sheffie', 'Audibert', '314-736-8439', '7548 Hansons Plaza', null, 'Saint Louis', 'MO', '63143');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Aleece', 'Stagg', '718-175-0344', '2105 Grayhawk Junction', null, 'New York City', 'NY', '10024');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Avivah', 'Cristol', '502-706-4164', '336 Reindahl Road', null, 'Louisville', 'KY', '40293');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Dorolice', 'Stegel', '215-396-5025', '52 Gateway Alley', null, 'Philadelphia', 'PA', '19191');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Neale', 'Kunze', '916-463-4696', '0013 Declaration Pass', null, 'Sacramento', 'CA', '95818');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Raynard', 'Poser', '512-816-2593', '088 Eggendart Parkway', null, 'Austin', 'TX', '78737');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Carmen', 'Brogioni', '315-146-5858', '0044 Forest Run Drive', null, 'Utica', 'NY', '13505');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Allyce', 'Sictornes', '651-843-1410', '303 Kings Place', null, 'Saint Paul', 'MN', '55127');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Tabbie', 'Heavy', '919-378-4990', '286 Shelley Hill', null, 'Durham', 'NC', '27717');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Clair', 'Tabbernor', '315-615-8384', '636 Melody Alley', null, 'Syracuse', 'NY', '13251');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Amargo', 'Berzin', '619-483-8504', '800 Killdeer Way', null, 'San Diego', 'CA', '92115');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Alexa', 'Kield', '585-881-8716', '85 Jana Lane', null, 'Rochester', 'NY', '14646');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Nora', 'Egginson', '281-147-4741', '1290 Bartillon Alley', null, 'Houston', 'TX', '77293');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Tabbie', 'Knowles', '516-138-5821', '277 Drewry Road', null, 'New Hyde Park', 'NY', '11044');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Heinrik', 'Longea', '804-465-3040', '24 6th Street', null, 'Richmond', 'VA', '23213');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Jacinthe', 'McInulty', '951-392-5919', '5708 Granby Center', null, 'Riverside', 'CA', '92519');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Evita', 'Salmon', '561-600-4476', '83 Coolidge Plaza', null, 'West Palm Beach', 'FL', '33405');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Ambur', 'Pardie', '915-606-7037', '24 Portage Road', null, 'El Paso', 'TX', '88535');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Matias', 'Sivil', '972-464-8079', '502 Marcy Terrace', null, 'Mesquite', 'TX', '75185');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Leandra', 'Kayes', '281-645-7837', '9319 Southridge Avenue', null, 'Humble', 'TX', '77346');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Giselle', 'Brisson', '512-231-9239', '005 Fremont Circle', null, 'Austin', 'TX', '78710');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Alaine', 'Hearmon', '719-120-6348', '02446 Clove Park', null, 'Colorado Springs', 'CO', '80995');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Donny', 'Hammon', '410-949-9317', '40 Brentwood Place', null, 'Baltimore', 'MD', '21211');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Cherri', 'Corrigan', '772-424-0622', '17381 Coolidge Alley', null, 'Vero Beach', 'FL', '32964');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Rollin', 'Bowmen', '901-794-5519', '4 Fallview Lane', null, 'Memphis', 'TN', '38161');
insert into dbo.Patients (PatientFirstName, PatientLastName, PatientPhoneNumber, PatientAddress1, PatientAddress2, PatientCity, PatientState, PatientZipcode) values ('Valeria', 'Emmison', '412-198-1427', '1164 Lukken Alley', null, 'Pittsburgh', 'PA', '15220');
Go
Select * From vPatients;

--100Appointments--
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (5, 16, 5, '7/25/2019 4:43 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (5, 25, 9, '1/6/2020 6:10 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (11, 89, 2, '10/6/2019 1:59 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (9, 43, 8, '2/3/2020 10:10 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (7, 9, 5, '3/5/2020 2:47 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (4, 8, 6, '7/4/2020 9:38 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (3, 51, 8, '11/3/2019 1:43 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (2, 44, 10, '10/30/2019 1:24 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (2, 57, 8, '4/12/2020 9:50 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (2, 74, 9, '12/14/2019 8:59 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (10, 13, 2, '10/7/2019 10:59 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (11, 76, 4, '11/2/2019 4:33 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (3, 89, 6, '4/22/2020 1:53 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (8, 61, 6, '9/27/2019 10:35 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (2, 76, 9, '4/14/2020 12:54 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (7, 63, 11, '8/6/2019 2:53 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (7, 16, 8, '6/9/2020 4:52 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (2, 84, 8, '5/7/2020 1:52 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (7, 101, 7, '2/21/2020 9:02 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (3, 37, 7, '2/27/2020 6:21 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (11, 96, 3, '7/21/2020 1:58 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (9, 28, 2, '4/22/2020 3:49 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (5, 49, 10, '2/2/2020 4:05 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (11, 10, 6, '7/9/2020 6:21 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (3, 9, 5, '11/22/2019 5:26 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (2, 52, 3, '2/8/2020 12:15 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (6, 27, 3, '9/21/2019 8:23 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (6, 81, 7, '1/31/2020 1:57 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (10, 61, 3, '12/4/2019 8:02 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (6, 89, 4, '10/29/2019 6:52 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (2, 10, 10, '1/25/2020 4:49 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (11, 7, 10, '4/28/2020 2:15 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (4, 14, 7, '3/9/2020 4:41 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (9, 80, 6, '7/2/2020 4:30 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (4, 8, 5, '3/7/2020 6:12 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (9, 58, 6, '3/4/2020 8:05 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (9, 41, 4, '6/21/2020 3:51 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (6, 98, 9, '7/5/2020 9:24 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (3, 98, 11, '6/25/2020 10:01 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (3, 93, 6, '1/8/2020 6:34 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (7, 70, 10, '5/11/2020 9:52 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (8, 98, 9, '8/30/2019 6:11 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (2, 36, 4, '1/17/2020 9:59 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (11, 70, 9, '6/29/2020 5:54 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (11, 79, 5, '12/31/2019 12:40 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (10, 58, 10, '2/15/2020 11:05 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (5, 44, 4, '11/18/2019 10:38 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (11, 71, 2, '9/26/2019 10:21 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (4, 100, 8, '1/19/2020 11:20 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (5, 19, 9, '9/3/2019 6:09 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (2, 72, 7, '10/3/2019 2:35 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (4, 52, 6, '5/13/2020 10:42 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (6, 26, 4, '6/25/2020 9:44 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (11, 95, 6, '2/11/2020 5:28 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (10, 29, 3, '4/8/2020 7:03 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (6, 82, 10, '2/21/2020 2:20 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (9, 59, 7, '8/16/2019 4:05 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (2, 71, 6, '9/25/2019 11:08 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (2, 99, 8, '11/22/2019 4:27 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (9, 8, 8, '4/15/2020 7:22 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (10, 16, 8, '12/13/2019 12:56 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (2, 100, 10, '7/5/2020 1:03 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (11, 21, 8, '9/11/2019 9:39 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (2, 81, 8, '10/6/2019 6:00 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (10, 3, 6, '5/21/2020 9:14 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (7, 96, 10, '1/6/2020 6:16 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (3, 11, 4, '1/27/2020 4:47 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (9, 31, 2, '4/3/2020 8:11 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (11, 51, 8, '2/6/2020 2:50 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (2, 4, 10, '2/15/2020 10:56 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (8, 63, 7, '10/19/2019 11:45 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (4, 41, 6, '6/8/2020 4:47 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (3, 21, 6, '6/15/2020 5:25 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (4, 93, 3, '2/24/2020 12:26 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (5, 36, 4, '10/20/2019 11:53 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (7, 24, 11, '8/28/2019 5:32 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (10, 81, 11, '5/1/2020 6:57 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (7, 38, 7, '2/25/2020 7:47 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (4, 99, 7, '7/16/2020 8:00 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (5, 44, 5, '1/16/2020 6:06 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (3, 89, 10, '10/14/2019 2:49 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (11, 10, 8, '2/18/2020 10:54 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (2, 59, 10, '8/29/2019 1:04 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (3, 80, 11, '3/31/2020 11:00 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (9, 11, 5, '10/23/2019 12:44 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (10, 40, 5, '2/5/2020 1:35 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (5, 49, 2, '2/24/2020 11:07 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (5, 90, 6, '10/12/2019 3:26 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (11, 3, 2, '11/13/2019 7:29 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (7, 54, 9, '1/29/2020 4:29 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (7, 88, 11, '12/17/2019 7:01 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (3, 2, 3, '8/4/2019 1:30 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (6, 80, 4, '8/1/2019 4:12 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (4, 37, 6, '5/14/2020 11:00 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (5, 3, 4, '9/22/2019 7:36 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (10, 39, 2, '5/28/2020 4:59 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (3, 37, 10, '10/5/2019 2:36 PM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (3, 80, 11, '5/19/2020 11:16 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (3, 4, 6, '3/4/2020 11:00 AM');
insert into dbo.Appointments (ClinicID, PatientID, DoctorID, AppointmentDateAndTime) values (5, 26, 8, '7/8/2020 12:19 PM');
Go
Select * From vAppointments;
Select * From vAppointmentsByPatientsDoctorsAndClinics;